require "test_helper"

class ApplicationIdTest < ActiveSupport::TestCase
  test "generated ID is a valid UUID" do
    id = ApplicationId.generate
    assert_match(/\A[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\z/, id)
  end

  test "generated ID has version 7" do
    id = ApplicationId.generate
    # UUIDv7 has version bits set to 0111 (7) in the 13th hex char of the UUID
    version_char = id[14]
    assert_equal "7", version_char, "UUID version must be 7"
  end

  test "generated IDs are unique" do
    ids = Array.new(100) { ApplicationId.generate }
    assert_equal 100, ids.uniq.length, "All generated IDs must be unique"
  end

  test "generated IDs are sortable by time" do
    ids = []
    10.times do
      ids << ApplicationId.generate
      sleep(0.001)
    end
    sorted = ids.sort
    assert_equal ids, sorted, "IDs must be in insertion order when sorted"
  end

  test "IDs are generated server-side, never client-provided" do
    assert_respond_to ApplicationId, :generate
  end

  test "client-provided IDs are rejected by persistence models" do
    user = User.new(
      id: "client-chosen-id",
      email: "client-id@example.com",
      password: "password123",
      full_name: "Client ID"
    )

    assert_not user.valid?, "a client-provided ID must not be authoritative"
    assert_includes user.errors[:id], "must be generated by the server"
  end
end
