class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  before_validation :reject_client_provided_id

  private

  def reject_client_provided_id
    errors.add(:id, "must be generated by the server") if id.present? && new_record?
  end
end
